#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use Sys::Syslog qw(openlog syslog closelog);

use PVE::Notify;

my $severity = 'warning';
my $source = 'host';
my $summary = '';
my $message = '';
my $type = 'nazar-host-alert';

GetOptions(
    'severity=s' => \$severity,
    'source=s'   => \$source,
    'summary=s'  => \$summary,
    'subject=s'  => \$summary, # compatibility alias
    'message=s'  => \$message,
    'type=s'     => \$type,
) or die "usage: $0 [--severity warning|error|notice|info] [--source name] --summary text [--message text]\n";

if ($severity !~ /^(info|notice|warning|error)$/) {
    die "invalid severity '$severity'\n";
}

if ($message eq '') {
    local $/;
    $message = <STDIN> // '';
}

$summary =~ s/[\r\n]+/ /g;
$summary =~ s/^\s+|\s+$//g;
$summary = 'host alert' if $summary eq '';

$message =~ s/\r\n/\n/g;
$message =~ s/\r/\n/g;
$message = '(no message body provided)' if $message eq '';

my $data = PVE::Notify::common_template_data();
$data->{severity} = $severity;
$data->{source} = $source;
$data->{summary} = $summary;
$data->{message} = $message;
$data->{time_text} = strftime('%Y-%m-%d %H:%M:%S %z', localtime);

my $fields = {
    type => $type,
    hostname => $data->{hostname},
};

openlog('nazar-proxmox-notify', 'pid', 'daemon');

my $ok = eval {
    PVE::Notify::notify($severity, 'nazar-alert', $data, $fields);
    1;
};

if (!$ok) {
    my $err = $@ || 'unknown notification error';
    chomp $err;
    syslog('err', 'failed to send Proxmox notification: %s', $err);
    closelog();
    die "failed to send Proxmox notification: $err\n";
}

syslog('info', 'sent %s alert from %s: %s', $severity, $source, $summary);
closelog();
exit 0;
