# Nixpi server configuration — generated by `nix flake init -t github:alexradunet/nixpi`
#
# Customize nixpi-config.nix to enable/disable modules,
# then run: sudo nixos-rebuild switch --flake .
{
  description = "My Nixpi server";

  inputs = {
    nixpi.url = "github:alexradunet/nixpi";
    nixpkgs.follows = "nixpi/nixpkgs";
    nixpkgs-unstable.follows = "nixpi/nixpkgs-unstable";
  };

  outputs = { self, nixpi, nixpkgs, nixpkgs-unstable, ... }:
    let
      system = "x86_64-linux";
      pkgsUnstable = import nixpkgs-unstable {
        inherit system;
        config.allowUnfree = true;
      };
    in {
      nixosConfigurations.nixpi = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit pkgsUnstable; };
        modules = [
          nixpi.nixosModules.default
          ./hardware.nix
          ./nixpi-config.nix
        ];
      };
    };
}
