# Nixpi server configuration — generated by `nix flake init -t github:alexradunet/nixpi`
#
# Customize nixpi-config.nix to enable/disable modules,
# then run: sudo nixos-rebuild switch --flake .
{
  description = "My Nixpi server";

  inputs = {
    nixpi.url = "github:alexradunet/nixpi";
    nixpkgs.follows = "nixpi/nixpkgs";
    nixpkgs-unstable.follows = "nixpi/nixpkgs-unstable";
  };

  outputs =
    {
      self,
      nixpi,
      nixpkgs,
      nixpkgs-unstable,
      ...
    }:
    let
      system = "x86_64-linux"; # Change to "aarch64-linux" for Raspberry Pi
      pkgsUnstable = import nixpkgs-unstable {
        inherit system;
        config.allowUnfree = true;
      };
    in
    {
      # Replace "nixpi" below with your machine's hostname (run: hostname)
      nixosConfigurations.nixpi = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit pkgsUnstable; };
        modules = [
          nixpi.nixosModules.default
          ./hardware.nix
          ./nixpi-config.nix
        ];
      };
    };
}
