#!/usr/bin/env bash
set -euo pipefail

# Nixpi Setup Wizard — generates NixOS configuration for a new Nixpi server.
#
# When NIXPI_SETUP_GENERATE_ONLY=1, only the generator functions are exported
# (for testing). Otherwise, the full dialog TUI wizard runs.

# --- Config generator functions (testable without dialog) ---

generate_nixpi_config() {
  local hostname="" username="" timezone="UTC"
  local tailscale="true" syncthing="true" ttyd="true"
  local desktop="true" password_policy="true"
  local heartbeat="false" matrix="false"
  local output=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --hostname) hostname="$2"; shift 2 ;;
      --username) username="$2"; shift 2 ;;
      --timezone) timezone="$2"; shift 2 ;;
      --tailscale) tailscale="$2"; shift 2 ;;
      --syncthing) syncthing="$2"; shift 2 ;;
      --ttyd) ttyd="$2"; shift 2 ;;
      --desktop) desktop="$2"; shift 2 ;;
      --password-policy) password_policy="$2"; shift 2 ;;
      --heartbeat) heartbeat="$2"; shift 2 ;;
      --matrix) matrix="$2"; shift 2 ;;
      --output) output="$2"; shift 2 ;;
      *) echo "Unknown option: $1" >&2; return 1 ;;
    esac
  done

  cat > "$output" <<EOF
# Nixpi configuration — generated by nixpi setup
# Run \`sudo nixos-rebuild switch --flake .\` after changes.
{ config, lib, ... }:

{
  # --- Bootloader (UEFI / systemd-boot) ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # BIOS fallback (uncomment and adjust disk if needed):
  # boot.loader.grub.enable = true;
  # boot.loader.grub.devices = [ "/dev/sda" ];

  # --- Identity ---
  networking.hostName = "$hostname";
  nixpi.primaryUser = "$username";
  nixpi.timeZone = "$timezone";

  # --- Modules ---
  nixpi.tailscale.enable = $tailscale;
  nixpi.syncthing.enable = $syncthing;
  nixpi.ttyd.enable = $ttyd;
  nixpi.desktop.enable = $desktop;
  nixpi.passwordPolicy.enable = $password_policy;
  nixpi.objects.enable = true;
  nixpi.heartbeat.enable = $heartbeat;
  nixpi.channels.matrix.enable = $matrix;
}
EOF
}

generate_flake_nix() {
  local hostname="" output=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --hostname) hostname="$2"; shift 2 ;;
      --output) output="$2"; shift 2 ;;
      *) echo "Unknown option: $1" >&2; return 1 ;;
    esac
  done

  cat > "$output" <<'FLAKEEOF'
{
  description = "My Nixpi server";

  inputs = {
    nixpi.url = "github:alexradunet/nixpi";
    nixpkgs.follows = "nixpi/nixpkgs";
    nixpkgs-unstable.follows = "nixpi/nixpkgs-unstable";
  };

  outputs = { self, nixpi, nixpkgs, nixpkgs-unstable, ... }:
    let
      system = "x86_64-linux";
      pkgsUnstable = import nixpkgs-unstable {
        inherit system;
        config.allowUnfree = true;
      };
    in {
FLAKEEOF

  cat >> "$output" <<EOF
      nixosConfigurations.$hostname = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit pkgsUnstable; };
        modules = [
          nixpi.nixosModules.default
          ./hardware.nix
          ./nixpi-config.nix
        ];
      };
    };
}
EOF
}

# When sourced for testing, only export functions
if [[ "${NIXPI_SETUP_GENERATE_ONLY:-0}" == "1" ]]; then
  return 0 2>/dev/null || exit 0
fi

# --- Dialog TUI wizard (runs only when executed directly) ---

DIALOG=${DIALOG:-dialog}
TARGET_DIR="${1:-$HOME/nixpi-server}"

show_welcome() {
  $DIALOG --title "Nixpi Setup" --msgbox \
    "Welcome to Nixpi!\n\nThis wizard will configure your Nixpi server.\n\nTarget directory: $TARGET_DIR" \
    12 60
}

get_basic_info() {
  HOSTNAME=$($DIALOG --title "Hostname" --inputbox "Enter your server hostname:" 8 50 "$(hostname)" 3>&1 1>&2 2>&3) || exit 1
  USERNAME=$($DIALOG --title "Username" --inputbox "Enter your Linux username:" 8 50 "${SUDO_USER:-$(whoami)}" 3>&1 1>&2 2>&3) || exit 1
  TIMEZONE=$($DIALOG --title "Timezone" --menu "Select your timezone:" 20 60 12 \
    "UTC" "Coordinated Universal Time" \
    "US/Eastern" "Eastern Time" \
    "US/Central" "Central Time" \
    "US/Mountain" "Mountain Time" \
    "US/Pacific" "Pacific Time" \
    "Europe/London" "UK Time" \
    "Europe/Berlin" "Central European" \
    "Europe/Bucharest" "Eastern European" \
    "Asia/Tokyo" "Japan" \
    "Asia/Shanghai" "China" \
    "Australia/Sydney" "Australia Eastern" \
    "Other" "Enter custom timezone" \
    3>&1 1>&2 2>&3) || exit 1

  if [[ "$TIMEZONE" == "Other" ]]; then
    TIMEZONE=$($DIALOG --title "Custom Timezone" --inputbox "Enter timezone (e.g. America/New_York):" 8 50 "UTC" 3>&1 1>&2 2>&3) || exit 1
  fi
}

get_ai_config() {
  AI_PROVIDER=$($DIALOG --title "AI Provider" --menu "Select your AI provider:" 14 60 5 \
    "anthropic" "Anthropic (Claude)" \
    "openai" "OpenAI (GPT)" \
    "openai-codex" "OpenAI Codex" \
    "custom" "Custom (OpenAI-compatible)" \
    3>&1 1>&2 2>&3) || exit 1

  case "$AI_PROVIDER" in
    anthropic)  DEFAULT_MODEL="claude-sonnet-4-6" ;;
    openai)     DEFAULT_MODEL="gpt-4.1" ;;
    openai-codex) DEFAULT_MODEL="codex-mini-latest" ;;
    custom)     DEFAULT_MODEL="" ;;
  esac

  AI_MODEL=$($DIALOG --title "Model" --inputbox "Enter model name:" 8 50 "$DEFAULT_MODEL" 3>&1 1>&2 2>&3) || exit 1
  AI_KEY=$($DIALOG --title "API Key" --passwordbox "Enter your API key:" 8 60 3>&1 1>&2 2>&3) || exit 1

  AI_THINKING=$($DIALOG --title "Thinking Level" --menu "Select thinking level:" 12 60 4 \
    "low" "Fast, minimal reasoning" \
    "medium" "Balanced" \
    "high" "More thorough reasoning" \
    "xhigh" "Maximum reasoning depth" \
    3>&1 1>&2 2>&3) || exit 1
}

get_modules() {
  MODULES=$($DIALOG --title "Modules" --checklist "Select modules to enable:" 20 60 8 \
    "tailscale" "Tailscale VPN" ON \
    "syncthing" "Syncthing file sync" ON \
    "ttyd" "Web terminal" ON \
    "desktop" "GNOME desktop" ON \
    "password-policy" "Password policy (16+ chars)" ON \
    "heartbeat" "Periodic agent wake cycle" OFF \
    "matrix" "Matrix server + bridge" OFF \
    3>&1 1>&2 2>&3) || exit 1
}

module_enabled() {
  [[ "$MODULES" == *"$1"* ]] && echo "true" || echo "false"
}

show_review() {
  $DIALOG --title "Review" --yesno \
    "Hostname: $HOSTNAME\nUsername: $USERNAME\nTimezone: $TIMEZONE\nAI: $AI_PROVIDER / $AI_MODEL\nModules: $MODULES\n\nApply this configuration?" \
    14 60
}

apply_config() {
  mkdir -p "$TARGET_DIR"

  # Generate hardware config
  nixos-generate-config --show-hardware-config > "$TARGET_DIR/hardware.nix"

  # Generate flake.nix
  generate_flake_nix --hostname "$HOSTNAME" --output "$TARGET_DIR/flake.nix"

  # Generate nixpi-config.nix
  generate_nixpi_config \
    --hostname "$HOSTNAME" \
    --username "$USERNAME" \
    --timezone "$TIMEZONE" \
    --tailscale "$(module_enabled tailscale)" \
    --syncthing "$(module_enabled syncthing)" \
    --ttyd "$(module_enabled ttyd)" \
    --desktop "$(module_enabled desktop)" \
    --password-policy "$(module_enabled password-policy)" \
    --heartbeat "$(module_enabled heartbeat)" \
    --matrix "$(module_enabled matrix)" \
    --output "$TARGET_DIR/nixpi-config.nix"

  # Store API key
  install -d -m 0700 -o root -g root /etc/nixpi/secrets
  printf '%s=%s\n' "NIXPI_AI_API_KEY" "$AI_KEY" > /etc/nixpi/secrets/ai-provider.env
  chmod 0600 /etc/nixpi/secrets/ai-provider.env

  # Seed Pi settings.json
  local pi_dir="/var/lib/nixpi/agent"
  install -d -m 0755 "$pi_dir"
  if [[ ! -f "$pi_dir/settings.json" ]]; then
    cat > "$pi_dir/settings.json" <<PIEOF
{
  "skills": [],
  "packages": [],
  "defaultProvider": "$AI_PROVIDER",
  "defaultModel": "$AI_MODEL",
  "defaultThinkingLevel": "$AI_THINKING"
}
PIEOF
  fi

  # Initialize git repo for flake
  (cd "$TARGET_DIR" && git init && git add -A)

  # Apply NixOS config
  $DIALOG --title "Applying..." --infobox "Running nixos-rebuild switch...\nThis may take several minutes." 6 50
  (cd "$TARGET_DIR" && sudo nixos-rebuild switch --flake "path:.#$HOSTNAME") 2>&1 | \
    $DIALOG --title "Build Progress" --programbox 20 80

  # Mark setup complete
  install -d -m 0755 /etc/nixpi
  touch /etc/nixpi/.setup-complete

  $DIALOG --title "Success" --msgbox \
    "Nixpi is configured!\n\nConfig directory: $TARGET_DIR\nRebuild: cd $TARGET_DIR && sudo nixos-rebuild switch --flake ." \
    10 60
}

# --- Main ---
show_welcome
get_basic_info
get_ai_config
get_modules
show_review && apply_config
